const fs = require('fs');
const path = require('path');

// Major Indian cities with realistic data
const citiesData = [
  { 
    name: "Mumbai", 
    state: "Maharashtra", 
    hdi: 0.78, 
    gdpPerCapita: 125000, 
    literacyRate: 89.2, 
    lifeExpectancy: 72.5, 
    unemploymentRate: 4.8, 
    airQualityIndex: 145, 
    povertyRate: 8.2, 
    infantMortalityRate: 12.3, 
    renewableEnergy: 15.2, 
    giniCoefficient: 0.42 
  },
  { 
    name: "Delhi", 
    state: "Delhi", 
    hdi: 0.82, 
    gdpPerCapita: 135000, 
    literacyRate: 88.7, 
    lifeExpectancy: 73.2, 
    unemploymentRate: 5.1, 
    airQualityIndex: 165, 
    povertyRate: 6.8, 
    infantMortalityRate: 11.8, 
    renewableEnergy: 12.8, 
    giniCoefficient: 0.38 
  },
  { 
    name: "Bangalore", 
    state: "Karnataka", 
    hdi: 0.85, 
    gdpPerCapita: 145000, 
    literacyRate: 91.3, 
    lifeExpectancy: 74.8, 
    unemploymentRate: 3.2, 
    airQualityIndex: 95, 
    povertyRate: 4.5, 
    infantMortalityRate: 9.8, 
    renewableEnergy: 28.5, 
    giniCoefficient: 0.35 
  },
  { 
    name: "Hyderabad", 
    state: "Telangana", 
    hdi: 0.79, 
    gdpPerCapita: 115000, 
    literacyRate: 87.9, 
    lifeExpectancy: 72.1, 
    unemploymentRate: 4.5, 
    airQualityIndex: 125, 
    povertyRate: 7.2, 
    infantMortalityRate: 13.5, 
    renewableEnergy: 22.3, 
    giniCoefficient: 0.41 
  },
  { 
    name: "Chennai", 
    state: "Tamil Nadu", 
    hdi: 0.77, 
    gdpPerCapita: 105000, 
    literacyRate: 86.4, 
    lifeExpectancy: 71.8, 
    unemploymentRate: 5.8, 
    airQualityIndex: 135, 
    povertyRate: 8.9, 
    infantMortalityRate: 14.2, 
    renewableEnergy: 18.7, 
    giniCoefficient: 0.44 
  },
  { 
    name: "Kolkata", 
    state: "West Bengal", 
    hdi: 0.75, 
    gdpPerCapita: 95000, 
    literacyRate: 85.2, 
    lifeExpectancy: 70.8, 
    unemploymentRate: 6.2, 
    airQualityIndex: 155, 
    povertyRate: 10.5, 
    infantMortalityRate: 15.8, 
    renewableEnergy: 14.3, 
    giniCoefficient: 0.46 
  },
  { 
    name: "Pune", 
    state: "Maharashtra", 
    hdi: 0.81, 
    gdpPerCapita: 110000, 
    literacyRate: 90.1, 
    lifeExpectancy: 73.5, 
    unemploymentRate: 3.8, 
    airQualityIndex: 115, 
    povertyRate: 5.8, 
    infantMortalityRate: 11.2, 
    renewableEnergy: 25.6, 
    giniCoefficient: 0.37 
  },
  { 
    name: "Ahmedabad", 
    state: "Gujarat", 
    hdi: 0.76, 
    gdpPerCapita: 100000, 
    literacyRate: 87.3, 
    lifeExpectancy: 71.2, 
    unemploymentRate: 4.9, 
    airQualityIndex: 145, 
    povertyRate: 7.8, 
    infantMortalityRate: 13.8, 
    renewableEnergy: 20.4, 
    giniCoefficient: 0.43 
  },
  { 
    name: "Jaipur", 
    state: "Rajasthan", 
    hdi: 0.72, 
    gdpPerCapita: 85000, 
    literacyRate: 84.1, 
    lifeExpectancy: 69.8, 
    unemploymentRate: 5.5, 
    airQualityIndex: 135, 
    povertyRate: 9.2, 
    infantMortalityRate: 16.5, 
    renewableEnergy: 18.9, 
    giniCoefficient: 0.45 
  },
  { 
    name: "Surat", 
    state: "Gujarat", 
    hdi: 0.74, 
    gdpPerCapita: 95000, 
    literacyRate: 85.8, 
    lifeExpectancy: 70.5, 
    unemploymentRate: 4.2, 
    airQualityIndex: 125, 
    povertyRate: 6.5, 
    infantMortalityRate: 12.8, 
    renewableEnergy: 22.1, 
    giniCoefficient: 0.40 
  },
  { 
    name: "Lucknow", 
    state: "Uttar Pradesh", 
    hdi: 0.70, 
    gdpPerCapita: 75000, 
    literacyRate: 82.3, 
    lifeExpectancy: 68.5, 
    unemploymentRate: 6.8, 
    airQualityIndex: 165, 
    povertyRate: 12.5, 
    infantMortalityRate: 18.2, 
    renewableEnergy: 12.5, 
    giniCoefficient: 0.48 
  },
  { 
    name: "Kanpur", 
    state: "Uttar Pradesh", 
    hdi: 0.68, 
    gdpPerCapita: 70000, 
    literacyRate: 81.7, 
    lifeExpectancy: 67.8, 
    unemploymentRate: 7.2, 
    airQualityIndex: 175, 
    povertyRate: 13.8, 
    infantMortalityRate: 19.5, 
    renewableEnergy: 11.2, 
    giniCoefficient: 0.50 
  },
  { 
    name: "Nagpur", 
    state: "Maharashtra", 
    hdi: 0.73, 
    gdpPerCapita: 85000, 
    literacyRate: 86.2, 
    lifeExpectancy: 70.2, 
    unemploymentRate: 5.1, 
    airQualityIndex: 125, 
    povertyRate: 8.5, 
    infantMortalityRate: 14.8, 
    renewableEnergy: 19.8, 
    giniCoefficient: 0.44 
  },
  { 
    name: "Indore", 
    state: "Madhya Pradesh", 
    hdi: 0.71, 
    gdpPerCapita: 80000, 
    literacyRate: 84.8, 
    lifeExpectancy: 69.5, 
    unemploymentRate: 5.8, 
    airQualityIndex: 135, 
    povertyRate: 9.8, 
    infantMortalityRate: 16.2, 
    renewableEnergy: 17.5, 
    giniCoefficient: 0.46 
  },
  { 
    name: "Thane", 
    state: "Maharashtra", 
    hdi: 0.79, 
    gdpPerCapita: 105000, 
    literacyRate: 88.9, 
    lifeExpectancy: 72.8, 
    unemploymentRate: 4.1, 
    airQualityIndex: 115, 
    povertyRate: 6.2, 
    infantMortalityRate: 11.8, 
    renewableEnergy: 24.3, 
    giniCoefficient: 0.39 
  },
  { 
    name: "Bhopal", 
    state: "Madhya Pradesh", 
    hdi: 0.69, 
    gdpPerCapita: 75000, 
    literacyRate: 83.1, 
    lifeExpectancy: 68.8, 
    unemploymentRate: 6.5, 
    airQualityIndex: 145, 
    povertyRate: 11.2, 
    infantMortalityRate: 17.5, 
    renewableEnergy: 15.8, 
    giniCoefficient: 0.47 
  },
  { 
    name: "Visakhapatnam", 
    state: "Andhra Pradesh", 
    hdi: 0.72, 
    gdpPerCapita: 85000, 
    literacyRate: 85.6, 
    lifeExpectancy: 70.1, 
    unemploymentRate: 5.2, 
    airQualityIndex: 115, 
    povertyRate: 8.8, 
    infantMortalityRate: 15.2, 
    renewableEnergy: 20.1, 
    giniCoefficient: 0.43 
  },
  { 
    name: "Pimpri-Chinchwad", 
    state: "Maharashtra", 
    hdi: 0.80, 
    gdpPerCapita: 110000, 
    literacyRate: 89.5, 
    lifeExpectancy: 73.2, 
    unemploymentRate: 3.9, 
    airQualityIndex: 105, 
    povertyRate: 5.5, 
    infantMortalityRate: 10.8, 
    renewableEnergy: 26.7, 
    giniCoefficient: 0.36 
  },
  { 
    name: "Patna", 
    state: "Bihar", 
    hdi: 0.65, 
    gdpPerCapita: 65000, 
    literacyRate: 79.8, 
    lifeExpectancy: 66.5, 
    unemploymentRate: 8.2, 
    airQualityIndex: 185, 
    povertyRate: 15.8, 
    infantMortalityRate: 22.5, 
    renewableEnergy: 9.8, 
    giniCoefficient: 0.52 
  },
  { 
    name: "Vadodara", 
    state: "Gujarat", 
    hdi: 0.75, 
    gdpPerCapita: 95000, 
    literacyRate: 86.7, 
    lifeExpectancy: 71.5, 
    unemploymentRate: 4.8, 
    airQualityIndex: 135, 
    povertyRate: 7.5, 
    infantMortalityRate: 13.2, 
    renewableEnergy: 21.4, 
    giniCoefficient: 0.42 
  },
  { 
    name: "Ghaziabad", 
    state: "Uttar Pradesh", 
    hdi: 0.71, 
    gdpPerCapita: 80000, 
    literacyRate: 84.2, 
    lifeExpectancy: 69.2, 
    unemploymentRate: 5.9, 
    airQualityIndex: 175, 
    povertyRate: 10.2, 
    infantMortalityRate: 16.8, 
    renewableEnergy: 13.6, 
    giniCoefficient: 0.45 
  },
  { 
    name: "Ludhiana", 
    state: "Punjab", 
    hdi: 0.74, 
    gdpPerCapita: 90000, 
    literacyRate: 85.9, 
    lifeExpectancy: 70.8, 
    unemploymentRate: 4.7, 
    airQualityIndex: 145, 
    povertyRate: 7.8, 
    infantMortalityRate: 14.5, 
    renewableEnergy: 18.9, 
    giniCoefficient: 0.43 
  },
  { 
    name: "Agra", 
    state: "Uttar Pradesh", 
    hdi: 0.67, 
    gdpPerCapita: 70000, 
    literacyRate: 82.1, 
    lifeExpectancy: 67.5, 
    unemploymentRate: 6.8, 
    airQualityIndex: 165, 
    povertyRate: 12.8, 
    infantMortalityRate: 18.9, 
    renewableEnergy: 12.3, 
    giniCoefficient: 0.49 
  },
  { 
    name: "Nashik", 
    state: "Maharashtra", 
    hdi: 0.73, 
    gdpPerCapita: 85000, 
    literacyRate: 86.4, 
    lifeExpectancy: 70.5, 
    unemploymentRate: 5.3, 
    airQualityIndex: 125, 
    povertyRate: 8.2, 
    infantMortalityRate: 14.8, 
    renewableEnergy: 19.5, 
    giniCoefficient: 0.44 
  },
  { 
    name: "Faridabad", 
    state: "Haryana", 
    hdi: 0.72, 
    gdpPerCapita: 85000, 
    literacyRate: 85.1, 
    lifeExpectancy: 70.2, 
    unemploymentRate: 5.5, 
    airQualityIndex: 155, 
    povertyRate: 9.5, 
    infantMortalityRate: 15.8, 
    renewableEnergy: 16.8, 
    giniCoefficient: 0.45 
  },
  { 
    name: "Meerut", 
    state: "Uttar Pradesh", 
    hdi: 0.68, 
    gdpPerCapita: 75000, 
    literacyRate: 83.2, 
    lifeExpectancy: 68.1, 
    unemploymentRate: 6.9, 
    airQualityIndex: 175, 
    povertyRate: 11.8, 
    infantMortalityRate: 17.5, 
    renewableEnergy: 13.2, 
    giniCoefficient: 0.48 
  },
  { 
    name: "Rajkot", 
    state: "Gujarat", 
    hdi: 0.73, 
    gdpPerCapita: 85000, 
    literacyRate: 86.1, 
    lifeExpectancy: 70.8, 
    unemploymentRate: 4.9, 
    airQualityIndex: 135, 
    povertyRate: 7.9, 
    infantMortalityRate: 14.2, 
    renewableEnergy: 20.8, 
    giniCoefficient: 0.43 
  },
  { 
    name: "Kalyan-Dombivali", 
    state: "Maharashtra", 
    hdi: 0.76, 
    gdpPerCapita: 95000, 
    literacyRate: 87.8, 
    lifeExpectancy: 71.5, 
    unemploymentRate: 4.6, 
    airQualityIndex: 125, 
    povertyRate: 7.2, 
    infantMortalityRate: 13.5, 
    renewableEnergy: 22.1, 
    giniCoefficient: 0.41 
  },
  { 
    name: "Vasai-Virar", 
    state: "Maharashtra", 
    hdi: 0.75, 
    gdpPerCapita: 90000, 
    literacyRate: 87.2, 
    lifeExpectancy: 71.2, 
    unemploymentRate: 4.8, 
    airQualityIndex: 115, 
    povertyRate: 7.8, 
    infantMortalityRate: 13.8, 
    renewableEnergy: 21.5, 
    giniCoefficient: 0.42 
  },
  { 
    name: "Varanasi", 
    state: "Uttar Pradesh", 
    hdi: 0.66, 
    gdpPerCapita: 70000, 
    literacyRate: 81.5, 
    lifeExpectancy: 67.2, 
    unemploymentRate: 7.1, 
    airQualityIndex: 175, 
    povertyRate: 13.2, 
    infantMortalityRate: 19.2, 
    renewableEnergy: 11.8, 
    giniCoefficient: 0.50 
  },
  { 
    name: "Srinagar", 
    state: "Jammu and Kashmir", 
    hdi: 0.69, 
    gdpPerCapita: 75000, 
    literacyRate: 83.8, 
    lifeExpectancy: 68.5, 
    unemploymentRate: 6.8, 
    airQualityIndex: 125, 
    povertyRate: 10.8, 
    infantMortalityRate: 16.5, 
    renewableEnergy: 15.2, 
    giniCoefficient: 0.46 
  },
  { 
    name: "Aurangabad", 
    state: "Maharashtra", 
    hdi: 0.71, 
    gdpPerCapita: 80000, 
    literacyRate: 84.9, 
    lifeExpectancy: 69.8, 
    unemploymentRate: 5.7, 
    airQualityIndex: 135, 
    povertyRate: 9.2, 
    infantMortalityRate: 15.8, 
    renewableEnergy: 18.3, 
    giniCoefficient: 0.45 
  },
  { 
    name: "Dhanbad", 
    state: "Jharkhand", 
    hdi: 0.64, 
    gdpPerCapita: 65000, 
    literacyRate: 80.2, 
    lifeExpectancy: 66.8, 
    unemploymentRate: 8.5, 
    airQualityIndex: 195, 
    povertyRate: 16.2, 
    infantMortalityRate: 23.5, 
    renewableEnergy: 8.9, 
    giniCoefficient: 0.53 
  },
  { 
    name: "Amritsar", 
    state: "Punjab", 
    hdi: 0.72, 
    gdpPerCapita: 85000, 
    literacyRate: 85.3, 
    lifeExpectancy: 70.1, 
    unemploymentRate: 5.2, 
    airQualityIndex: 145, 
    povertyRate: 8.5, 
    infantMortalityRate: 15.2, 
    renewableEnergy: 17.8, 
    giniCoefficient: 0.44 
  },
  { 
    name: "Allahabad", 
    state: "Uttar Pradesh", 
    hdi: 0.67, 
    gdpPerCapita: 70000, 
    literacyRate: 82.4, 
    lifeExpectancy: 67.8, 
    unemploymentRate: 6.9, 
    airQualityIndex: 165, 
    povertyRate: 12.5, 
    infantMortalityRate: 18.5, 
    renewableEnergy: 12.8, 
    giniCoefficient: 0.49 
  },
  { 
    name: "Ranchi", 
    state: "Jharkhand", 
    hdi: 0.66, 
    gdpPerCapita: 70000, 
    literacyRate: 81.9, 
    lifeExpectancy: 67.2, 
    unemploymentRate: 7.8, 
    airQualityIndex: 155, 
    povertyRate: 14.2, 
    infantMortalityRate: 20.8, 
    renewableEnergy: 11.5, 
    giniCoefficient: 0.51 
  },
  { 
    name: "Howrah", 
    state: "West Bengal", 
    hdi: 0.68, 
    gdpPerCapita: 75000, 
    literacyRate: 83.1, 
    lifeExpectancy: 68.5, 
    unemploymentRate: 6.5, 
    airQualityIndex: 165, 
    povertyRate: 11.8, 
    infantMortalityRate: 17.2, 
    renewableEnergy: 13.9, 
    giniCoefficient: 0.47 
  },
  { 
    name: "Coimbatore", 
    state: "Tamil Nadu", 
    hdi: 0.74, 
    gdpPerCapita: 90000, 
    literacyRate: 86.8, 
    lifeExpectancy: 71.2, 
    unemploymentRate: 4.8, 
    airQualityIndex: 125, 
    povertyRate: 7.5, 
    infantMortalityRate: 13.8, 
    renewableEnergy: 20.5, 
    giniCoefficient: 0.42 
  },
  { 
    name: "Jabalpur", 
    state: "Madhya Pradesh", 
    hdi: 0.68, 
    gdpPerCapita: 75000, 
    literacyRate: 83.5, 
    lifeExpectancy: 68.2, 
    unemploymentRate: 6.2, 
    airQualityIndex: 145, 
    povertyRate: 10.5, 
    infantMortalityRate: 16.8, 
    renewableEnergy: 15.6, 
    giniCoefficient: 0.46 
  },
  { 
    name: "Gwalior", 
    state: "Madhya Pradesh", 
    hdi: 0.67, 
    gdpPerCapita: 70000, 
    literacyRate: 82.8, 
    lifeExpectancy: 67.8, 
    unemploymentRate: 6.8, 
    airQualityIndex: 155, 
    povertyRate: 11.2, 
    infantMortalityRate: 17.5, 
    renewableEnergy: 14.2, 
    giniCoefficient: 0.47 
  },
  { 
    name: "Vijayawada", 
    state: "Andhra Pradesh", 
    hdi: 0.71, 
    gdpPerCapita: 80000, 
    literacyRate: 85.2, 
    lifeExpectancy: 69.8, 
    unemploymentRate: 5.5, 
    airQualityIndex: 135, 
    povertyRate: 9.1, 
    infantMortalityRate: 15.5, 
    renewableEnergy: 18.9, 
    giniCoefficient: 0.44 
  },
  { 
    name: "Jodhpur", 
    state: "Rajasthan", 
    hdi: 0.69, 
    gdpPerCapita: 75000, 
    literacyRate: 83.9, 
    lifeExpectancy: 68.5, 
    unemploymentRate: 6.1, 
    airQualityIndex: 145, 
    povertyRate: 10.8, 
    infantMortalityRate: 16.2, 
    renewableEnergy: 16.5, 
    giniCoefficient: 0.45 
  },
  { 
    name: "Madurai", 
    state: "Tamil Nadu", 
    hdi: 0.70, 
    gdpPerCapita: 80000, 
    literacyRate: 84.6, 
    lifeExpectancy: 69.2, 
    unemploymentRate: 5.8, 
    airQualityIndex: 135, 
    povertyRate: 9.8, 
    infantMortalityRate: 16.5, 
    renewableEnergy: 17.8, 
    giniCoefficient: 0.46 
  },
  { 
    name: "Raipur", 
    state: "Chhattisgarh", 
    hdi: 0.65, 
    gdpPerCapita: 70000, 
    literacyRate: 81.2, 
    lifeExpectancy: 67.5, 
    unemploymentRate: 7.5, 
    airQualityIndex: 155, 
    povertyRate: 13.5, 
    infantMortalityRate: 19.8, 
    renewableEnergy: 12.8, 
    giniCoefficient: 0.49 
  },
  { 
    name: "Kota", 
    state: "Rajasthan", 
    hdi: 0.71, 
    gdpPerCapita: 80000, 
    literacyRate: 85.1, 
    lifeExpectancy: 69.8, 
    unemploymentRate: 5.3, 
    airQualityIndex: 135, 
    povertyRate: 8.9, 
    infantMortalityRate: 15.2, 
    renewableEnergy: 18.2, 
    giniCoefficient: 0.43 
  },
  { 
    name: "Chandigarh", 
    state: "Chandigarh", 
    hdi: 0.84, 
    gdpPerCapita: 120000, 
    literacyRate: 90.8, 
    lifeExpectancy: 74.2, 
    unemploymentRate: 3.5, 
    airQualityIndex: 105, 
    povertyRate: 4.2, 
    infantMortalityRate: 9.5, 
    renewableEnergy: 26.8, 
    giniCoefficient: 0.34 
  },
  { 
    name: "Guwahati", 
    state: "Assam", 
    hdi: 0.68, 
    gdpPerCapita: 75000, 
    literacyRate: 83.4, 
    lifeExpectancy: 68.8, 
    unemploymentRate: 6.4, 
    airQualityIndex: 145, 
    povertyRate: 11.5, 
    infantMortalityRate: 17.2, 
    renewableEnergy: 15.8, 
    giniCoefficient: 0.46 
  },
  { 
    name: "Solapur", 
    state: "Maharashtra", 
    hdi: 0.70, 
    gdpPerCapita: 80000, 
    literacyRate: 84.7, 
    lifeExpectancy: 69.5, 
    unemploymentRate: 5.9, 
    airQualityIndex: 135, 
    povertyRate: 9.5, 
    infantMortalityRate: 16.2, 
    renewableEnergy: 18.5, 
    giniCoefficient: 0.45 
  },
  { 
    name: "Hubli-Dharwad", 
    state: "Karnataka", 
    hdi: 0.72, 
    gdpPerCapita: 85000, 
    literacyRate: 85.8, 
    lifeExpectancy: 70.2, 
    unemploymentRate: 5.1, 
    airQualityIndex: 125, 
    povertyRate: 8.2, 
    infantMortalityRate: 14.8, 
    renewableEnergy: 19.8, 
    giniCoefficient: 0.43 
  },
  { 
    name: "Mysore", 
    state: "Karnataka", 
    hdi: 0.73, 
    gdpPerCapita: 85000, 
    literacyRate: 86.2, 
    lifeExpectancy: 70.5, 
    unemploymentRate: 4.9, 
    airQualityIndex: 115, 
    povertyRate: 7.8, 
    infantMortalityRate: 14.2, 
    renewableEnergy: 20.5, 
    giniCoefficient: 0.42 
  },
  { 
    name: "Tiruchirappalli", 
    state: "Tamil Nadu", 
    hdi: 0.71, 
    gdpPerCapita: 80000, 
    literacyRate: 85.1, 
    lifeExpectancy: 69.8, 
    unemploymentRate: 5.6, 
    airQualityIndex: 125, 
    povertyRate: 8.9, 
    infantMortalityRate: 15.5, 
    renewableEnergy: 18.9, 
    giniCoefficient: 0.44 
  },
  { 
    name: "Bareilly", 
    state: "Uttar Pradesh", 
    hdi: 0.65, 
    gdpPerCapita: 70000, 
    literacyRate: 81.8, 
    lifeExpectancy: 67.2, 
    unemploymentRate: 7.2, 
    airQualityIndex: 175, 
    povertyRate: 13.8, 
    infantMortalityRate: 19.5, 
    renewableEnergy: 11.8, 
    giniCoefficient: 0.50 
  },
  { 
    name: "Aligarh", 
    state: "Uttar Pradesh", 
    hdi: 0.66, 
    gdpPerCapita: 70000, 
    literacyRate: 82.1, 
    lifeExpectancy: 67.5, 
    unemploymentRate: 7.0, 
    airQualityIndex: 165, 
    povertyRate: 13.2, 
    infantMortalityRate: 18.8, 
    renewableEnergy: 12.5, 
    giniCoefficient: 0.49 
  },
  { 
    name: "Moradabad", 
    state: "Uttar Pradesh", 
    hdi: 0.64, 
    gdpPerCapita: 65000, 
    literacyRate: 80.5, 
    lifeExpectancy: 66.8, 
    unemploymentRate: 7.8, 
    airQualityIndex: 185, 
    povertyRate: 15.2, 
    infantMortalityRate: 21.5, 
    renewableEnergy: 10.8, 
    giniCoefficient: 0.51 
  },
  { 
    name: "Gurgaon", 
    state: "Haryana", 
    hdi: 0.83, 
    gdpPerCapita: 130000, 
    literacyRate: 89.7, 
    lifeExpectancy: 73.8, 
    unemploymentRate: 3.8, 
    airQualityIndex: 155, 
    povertyRate: 5.2, 
    infantMortalityRate: 10.5, 
    renewableEnergy: 24.2, 
    giniCoefficient: 0.37 
  },
  { 
    name: "Noida", 
    state: "Uttar Pradesh", 
    hdi: 0.82, 
    gdpPerCapita: 125000, 
    literacyRate: 89.2, 
    lifeExpectancy: 73.5, 
    unemploymentRate: 4.0, 
    airQualityIndex: 145, 
    povertyRate: 5.8, 
    infantMortalityRate: 11.2, 
    renewableEnergy: 23.5, 
    giniCoefficient: 0.38 
  }
];

function generateMetrics(cityData) {
  const baseMetrics = cityData;
  
  // Generate additional indices based on base metrics
  const metrics = {
    year: 2023,
    hdi: baseMetrics.hdi,
    gdpPerCapita: baseMetrics.gdpPerCapita,
    literacyRate: baseMetrics.literacyRate,
    lifeExpectancy: baseMetrics.lifeExpectancy,
    unemploymentRate: baseMetrics.unemploymentRate,
    airQualityIndex: baseMetrics.airQualityIndex,
    povertyRate: baseMetrics.povertyRate,
    infantMortalityRate: baseMetrics.infantMortalityRate,
    renewableEnergy: baseMetrics.renewableEnergy,
    giniCoefficient: baseMetrics.giniCoefficient,
    
    // Derived indices
    educationIndex: baseMetrics.literacyRate / 100,
    healthcareIndex: baseMetrics.lifeExpectancy / 85,
    infrastructureIndex: (100 - baseMetrics.unemploymentRate) / 100 * 0.8 + 0.2,
    digitalIndex: (baseMetrics.literacyRate / 100) * 0.7 + (baseMetrics.gdpPerCapita / 150000) * 0.3,
    innovationIndex: (baseMetrics.gdpPerCapita / 150000) * 0.6 + (baseMetrics.literacyRate / 100) * 0.4,
    sustainabilityIndex: (baseMetrics.renewableEnergy / 50) * 0.5 + ((100 - baseMetrics.airQualityIndex) / 100) * 0.5,
    tourismIndex: Math.random() * 0.3 + 0.6,
    manufacturingIndex: Math.random() * 0.3 + 0.6,
    servicesIndex: Math.random() * 0.3 + 0.7,
    agricultureIndex: Math.random() * 0.4 + 0.1,
    transportIndex: Math.random() * 0.3 + 0.6,
    housingIndex: Math.random() * 0.4 + 0.5,
    waterIndex: Math.random() * 0.3 + 0.6,
    wasteIndex: Math.random() * 0.3 + 0.6,
    greenSpaceIndex: Math.random() * 0.4 + 0.4,
    crimeIndex: Math.random() * 0.4 + 0.5,
    genderEqualityIndex: Math.random() * 0.3 + 0.6,
    youthIndex: Math.random() * 0.3 + 0.7,
    elderlyIndex: Math.random() * 0.3 + 0.6,
    disabilityIndex: Math.random() * 0.3 + 0.6,
    migrationIndex: Math.random() * 0.3 + 0.7,
    culturalIndex: Math.random() * 0.3 + 0.7,
    sportsIndex: Math.random() * 0.3 + 0.6,
    mediaIndex: Math.random() * 0.3 + 0.7,
    financeIndex: Math.random() * 0.3 + 0.7,
    technologyIndex: Math.random() * 0.3 + 0.7,
    researchIndex: Math.random() * 0.3 + 0.7,
    startupIndex: Math.random() * 0.3 + 0.7,
    internationalIndex: Math.random() * 0.3 + 0.6
  };

  // Normalize all indices to 0-1 range
  Object.keys(metrics).forEach(key => {
    if (key !== 'year' && key !== 'gdpPerCapita' && key !== 'literacyRate' && key !== 'lifeExpectancy' && 
        key !== 'unemploymentRate' && key !== 'airQualityIndex' && key !== 'povertyRate' && 
        key !== 'infantMortalityRate' && key !== 'renewableEnergy' && key !== 'giniCoefficient') {
      metrics[key] = Math.min(1, Math.max(0, metrics[key]));
    }
  });

  return metrics;
}

function generateCities() {
  const cities = citiesData.map((cityData, index) => ({
    _id: (index + 1).toString(),
    name: cityData.name,
    state: cityData.state,
    metrics: [generateMetrics(cityData)]
  }));

  return cities;
}

// Generate and save the data
const cities = generateCities();
const outputPath = path.join(__dirname, '..', 'data', 'cities.json');

fs.writeFileSync(outputPath, JSON.stringify(cities, null, 2));
console.log(`Generated data for ${cities.length} cities and saved to ${outputPath}`);

module.exports = { generateCities }; 